/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.Seleccion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.*;
import static recursos.conexion.conexion.obtenerConexion;
/**
 *
 * @author lizet
 */
public class CandidatoForm extends javax.swing.JFrame {
    private final JTextField txtCedula;
    private final JTextField txtNombre;
    private final JTextArea txtArea;
    private final JButton btnGuardar;
    private final JButton btnMostrar;
    /**
     * Creates new form CandidatoForm
     */
    public CandidatoForm() {
        initComponents();
        setTitle("Gestión de Candidatos");
        setLayout(null);
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Etiqueta y campo para la Cédula
        JLabel lblCedula = new JLabel("Cédula:");
        lblCedula.setBounds(21, 20, 100, 25);
        add(lblCedula);

        txtCedula = new JTextField();
        txtCedula.setBounds(120, 20, 150, 25);
        add(txtCedula);

        // Etiqueta y campo para el Nombre
        JLabel lblNombre = new JLabel("Nombre:");
        lblNombre.setBounds(20, 60, 100, 25);
        add(lblNombre);

        txtNombre = new JTextField();
        txtNombre.setBounds(120, 60, 150, 25);
        add(txtNombre);

        // Botón para guardar datos
        btnGuardar = new JButton("Guardar");
        btnGuardar.setBounds(20, 100, 100, 25);
        add(btnGuardar);

        // Botón para mostrar los datos
        btnMostrar = new JButton("Mostrar");
        btnMostrar.setBounds(150, 100, 100, 25);
        add(btnMostrar);

        // Área de texto para mostrar los datos
        txtArea = new JTextArea();
        txtArea.setBounds(20, 140, 300, 100);
        txtArea.setEditable(false);
        add(txtArea);
        btnGuardar.addActionListener((ActionEvent e) -> {
            guardarCandidato();
        });

        btnMostrar.addActionListener((ActionEvent e) -> {
            mostrarCandidatos();
        });

        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void guardarCandidato() {
    try (Connection conexion = obtenerConexion()) {
        String sql = "INSERT INTO CANDIDATOS (CEDULA, NOMBRE) VALUES (?, ?)";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setString(1, txtCedula.getText());
            ps.setString(2, txtNombre.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Candidato guardado correctamente");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
    }
}

    // Método para mostrar todos los candidatos
    private void mostrarCandidatos() {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        txtArea.setText(""); // Limpiar el área de texto
        try {
            conn = obtenerConexion();
            stmt = conn.createStatement();
            String sql = "SELECT cedula, nombre FROM candidatos";
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String cedula = rs.getString("cedula");
                String nombre = rs.getString("nombre");
                txtArea.append("Cédula: " + cedula + ", Nombre: " + nombre + "\n");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al mostrar: " + ex.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
            }
        }
    }
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidatoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidatoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidatoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidatoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CandidatoForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
