/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.Seleccion;
import javax.swing.*;
/**
 *
 * @author lizet
 */
public class EvaluacionForm extends javax.swing.JFrame {
private JLabel lblTitulo, lblId, lblCandidato, lblPuntaje;
    private JTextField txtId, txtCandidato, txtPuntaje;
    private JButton btnGuardar, btnCancelar;

    /**
     * Creates new form EvaluacionForm
     */
    public EvaluacionForm() {
        initComponents();
    }
private void initComponents() {

        lblTitulo = new JLabel("Formulario de Evaluación");
        lblId = new JLabel("ID Evaluación:");
        lblCandidato = new JLabel("Candidato:");
        lblPuntaje = new JLabel("Puntaje:");

        txtId = new JTextField(20);
        txtCandidato = new JTextField(20);
        txtPuntaje = new JTextField(5);

        btnGuardar = new JButton("Guardar");
        btnCancelar = new JButton("Cancelar");

        setTitle("Evaluación");
        setLayout(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Posiciones
        lblTitulo.setBounds(130, 10, 200, 30);
        lblId.setBounds(50, 50, 100, 20);
        txtId.setBounds(150, 50, 200, 20);
        lblCandidato.setBounds(50, 80, 100, 20);
        txtCandidato.setBounds(150, 80, 200, 20);
        lblPuntaje.setBounds(50, 110, 100, 20);
        txtPuntaje.setBounds(150, 110, 200, 20);
        btnGuardar.setBounds(100, 150, 100, 30);
        btnCancelar.setBounds(220, 150, 100, 30);

        // Añadir componentes
        add(lblTitulo);
        add(lblId);
        add(txtId);
        add(lblCandidato);
        add(txtCandidato);
        add(lblPuntaje);
        add(txtPuntaje);
        add(btnGuardar);
        add(btnCancelar);

        setSize(400, 250);
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvaluacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvaluacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvaluacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvaluacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvaluacionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
